### ISSUE TITLE
[BUG] Not able to fetch Image while deploying helm charts

### ISSUE THREAD

**Issue by dhruvinmaniar123** [prestodb/presto-helm-charts#3]
While installing the fresh helm charts I am facing below issue:

```
Events:
  Type     Reason          Age                    From     Message
  ----     ------          ----                   ----     -------
  Normal   BackOff         15h (x2855 over 26h)   kubelet  Back-off pulling image "ahanaio/prestodb:0.281"
  Normal   SandboxChanged  3h28m                  kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling         3h26m (x4 over 3h28m)  kubelet  Pulling image "ahanaio/prestodb:0.281"
  Warning  Failed          3h26m (x4 over 3h28m)  kubelet  Failed to pull image "ahanaio/prestodb:0.281": Error response from daemon: pull access denied for ahanaio/prestodb, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed          3h26m (x4 over 3h28m)  kubelet  Error: ErrImagePull
  Warning  Failed          3h26m (x6 over 3h28m)  kubelet  Error: ImagePullBackOff
  Normal   BackOff         67s (x127 over 3h28m)  kubelet  Back-off pulling image "ahanaio/prestodb:0.281"
```

Can someone please look into it?

**Comment by tdcmeehan** [comment]
Are you using the latest chart?  03f9d7718e2f151953a683b6baeac9c3a101e8e6 should have moved this to the official Presto image--Ahana images are deprecated and removed.

**Comment by dhruvinmaniar123** [comment]
@tdcmeehan I am deploying through argocd application and I had to override the tag value to the latest and it worked. Isn't this possible with the default value? In my case it's taking the older one.

**Comment by dnskr** [comment]
Hi @dhruvinmaniar123,
Default Presto image repo and tag have been changed to `prestodb/presto:0.284`, see commits https://github.com/prestodb/presto-helm-charts/commit/03f9d7718e2f151953a683b6baeac9c3a101e8e6 and https://github.com/prestodb/presto-helm-charts/commit/ea38112cfe38b7ab6968a32fcc35efa10f35a8ec.
The change has not been released yet, but I'm going to release the helm chart with the next Presto version.

**Comment by dnskr** [comment]
New version of the chart with the fix for the issue has been released!
See https://github.com/prestodb/presto-helm-charts/releases/tag/presto-0.2.0
